name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build dev image
        run: docker build -t brabodopedro/my-docker:dev .

      - name: Build prod image
        run: docker build -t brabodopedro/my-docker:latest .

      - name: Push dev image
        run: docker push brabodopedro/my-docker:dev

      - name: Push prod image
        run: docker push brabodopedro/my-docker:latest
